/**
 * Invoice.js
 *
 * The canonical Invoice record — one per payment / subscription.
 *
 * FLOW
 * ────
 * 1. Payment confirmed (Stripe card or wire marked-paid by admin)
 *    → invoiceService.createOrUpdateInvoice() is called
 *    → a new Invoice document is created with a unique invoice number
 *      generated by invoiceNumberService.generateInvoiceNumber()
 *
 * 2. Admin edits invoice fields via PATCH /api/payments/:id/save-invoice-draft
 *    → saveInvoiceDraft() in paymentController also calls
 *      invoiceService.createOrUpdateInvoice() with the updated fields
 *    → the SAME Invoice document is updated (upsert by paymentId)
 *
 * 3. User's SubscriptionPage and Admin dashboard both fetch the Invoice
 *    via GET /api/invoices/by-payment/:paymentId or by-registration/:regId
 *    → both see the same document → identical PDF every time
 *
 * SINGLE SOURCE OF TRUTH
 * ──────────────────────
 * Payment.invoiceDraft  — kept for backward compat but Invoice is authoritative
 * Invoice.draft         — the admin-editable fields that go into the PDF
 * Invoice.invoiceNumber — the unique "Invoice US-350-26" string
 */
const mongoose = require('mongoose');

const LineItemSchema = new mongoose.Schema({
  description: { type: String, default: '' },
  quantity:    { type: Number, default: 1 },
  unitPrice:   { type: Number, default: 0 },
  totalPrice:  { type: Number, default: 0 },
}, { _id: false });

const InvoiceSchema = new mongoose.Schema({

  // ── Identity ────────────────────────────────────────────────────────────────
  invoiceNumber: { type: String, required: true, unique: true, index: true },

  // ── Links ───────────────────────────────────────────────────────────────────
  paymentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Payment',
    index: true,
    default: null,
  },
  registrationId: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    index: true,
  },
  registrationModel: {
    type: String,
    enum: ['Individual', 'Airlines', 'AirlinesSubscription'],
    required: true,
  },

  // ── Status ──────────────────────────────────────────────────────────────────
  status: {
    type: String,
    enum: ['draft', 'issued', 'paid', 'void'],
    default: 'issued',
    index: true,
  },

  // ── Dates ───────────────────────────────────────────────────────────────────
  issueDate:  { type: Date, default: Date.now },
  payableBy:  { type: Date },
  paidAt:     { type: Date },

  // ── Recipient (snapshot at invoice time) ────────────────────────────────────
  recipientName:     { type: String, default: '' },
  recipientCompany:  { type: String, default: '' },
  recipientContact:  { type: String, default: '' },
  recipientAddress1: { type: String, default: '' },
  recipientAddress2: { type: String, default: '' },
  recipientCountry:  { type: String, default: '' },
  recipientEmail:    { type: String, default: '' },
  recipientPhone:    { type: String, default: '' },

  // ── Subscription context ─────────────────────────────────────────────────────
  subscriptionPlan: { type: String, default: '' },
  subscriptionDate: { type: Date },
  expirationDate:   { type: Date },
  isAirline:        { type: Boolean, default: false },

  // ── Financial ───────────────────────────────────────────────────────────────
  lineItems:     { type: [LineItemSchema], default: [] },
  subtotal:      { type: Number, default: 0 },
  tax:           { type: Number, default: 0 },
  totalAmount:   { type: Number, default: 0 },
  currency:      { type: String, default: 'USD' },
  paymentMethod: { type: String, default: '' },

  // ── Admin-editable draft ────────────────────────────────────────────────────
  // When admin edits invoice fields in the dashboard the full PDF-ready
  // payload is stored here. Both the admin view and user SubscriptionPage
  // read from this field to generate the PDF.
  draft: {
    type: mongoose.Schema.Types.Mixed,
    default: null,
  },

  // ── Generation flag ─────────────────────────────────────────────────────────
  // true  = admin has explicitly generated / downloaded this invoice at least once
  // false = auto-generated from payment data (user can still download it)
  adminGenerated: { type: Boolean, default: false },

}, { timestamps: true });

module.exports = mongoose.model('Invoice', InvoiceSchema);
