/**
 * InvoiceModal.jsx
 *
 * SINGLE SOURCE OF TRUTH FOR INVOICE DISPLAY & DOWNLOAD
 * ──────────────────────────────────────────────────────
 * This component is the only place that renders and downloads an invoice PDF
 * for end-users (subscription page) AND for the admin when viewing a user's
 * invoice. Both paths feed the same `invoice` prop shape so the output is
 * always identical.
 *
 * Invoice data priority (highest → lowest):
 *   1. Payment.invoiceDraft  — admin-edited fields saved via PATCH /payments/:id/save-invoice-draft
 *   2. Payment.invoiceSnapshot — immutable snapshot captured at payment time
 *   3. Local fallback built from registration data (wire/legacy records only)
 *
 * The PDF is generated by ifoaInvoicePdf.js (shared util, also used by admin).
 */

import { useState } from 'react'
import { generateIFOAInvoicePDF, triggerInvoiceDownload } from '../../utils/ifoaInvoicePdf'

// ── Helpers ───────────────────────────────────────────────────────────────────
const fmt = (d) =>
  d ? new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—'

function toIsoDate(input) {
  if (!input) return ''
  const d = new Date(input)
  if (Number.isNaN(d.getTime())) return ''
  return d.toISOString().slice(0, 10)
}

function plusDays(dateIso, days) {
  const d = new Date(dateIso || Date.now())
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

/**
 * For airlines the total must always be pricePerCert × holderCount.
 * The stored `amount` / `amountDollars` on legacy records was saved with the
 * old flat-$265 bug, so we never trust it for airlines when we have both
 * pricePerCert and holderCount available.
 */
export function resolveAirlineTotal(inv) {
  const pricePerCert = Number(inv.pricePerCert) || 0
  const holderCount  = Number(inv.holderCount)  || 0
  if (pricePerCert > 0 && holderCount > 0) {
    return pricePerCert * holderCount
  }
  return Number(inv.amount) || 0
}

/**
 * Build the invoice shape expected by generateIFOAInvoicePDF().
 *
 * Priority:
 *   1. If invoice.invoiceDraft exists (admin saved edits) — use it verbatim.
 *      The draft is already in the exact shape generateIFOAInvoicePDF() expects.
 *   2. Otherwise build from invoiceSnapshot / payment fields.
 */
export function buildPDFPayload(inv) {
  // ── Path 1: admin-edited draft is the authoritative invoice ──────────────
  // Accept any non-null draft that has either lineItems or an invoiceNumber.
  // Always merge the parent invoiceNumber as a fallback so the PDF never shows
  // a blank or auto-generated number when the admin didn't explicitly set one.
  if (inv.invoiceDraft && typeof inv.invoiceDraft === 'object' &&
      (inv.invoiceDraft.lineItems?.length || inv.invoiceDraft.invoiceNumber)) {
    return {
      ...inv.invoiceDraft,
      invoiceNumber: inv.invoiceDraft.invoiceNumber || inv.invoiceNumber,
    }
  }

  // ── Path 2: build from payment/snapshot fields ────────────────────────────
  const issueDate   = toIsoDate(inv.paidAt) || toIsoDate(new Date())
  const quantity    = inv.isAirline ? (Number(inv.holderCount) || 1) : 1
  const unitPrice   = inv.isAirline
    ? (Number(inv.pricePerCert) || Number(inv.amount) || 0)
    : (Number(inv.amount) || 0)

  // Always recompute airline total from pricePerCert × holderCount
  const totalPrice  = inv.isAirline ? resolveAirlineTotal(inv) : (Number(inv.amount) || 0)

  const planDesc = `Agent For Service - ${(inv.subscriptionPlan || '1 Year Plan')
    .replace(' Subscription Plan', '')
    .replace(' Plan', '')}`

  return {
    invoiceNumber:     inv.invoiceNumber || `INV-${Date.now()}`,
    issueDate,
    payableBy:         plusDays(issueDate, 30),
    recipientCompany:  inv.isAirline ? (inv.airlineName || inv.name || '') : '',
    recipientName:     inv.name || '',
    recipientContact:  inv.name || '',
    recipientAddress1: inv.address || '',
    recipientAddress2: '',
    recipientCountry:  '',
    paymentMethod:     inv.paymentMethodType || 'card',
    lineItems: [
      {
        description: planDesc,
        quantity,
        unitPrice,
        totalPrice,  // ✅ pricePerCert × holderCount for airlines, not stale stored amount
      },
    ],
  }
}

// Export for use by admin dashboard so both use the same PDF generator
export async function downloadInvoicePDF(inv) {
  const payload   = buildPDFPayload(inv)
  const generated = await generateIFOAInvoicePDF(payload)
  triggerInvoiceDownload(generated)
}

// ── Invoice Preview Modal ─────────────────────────────────────────────────────
export default function InvoiceModal({ invoice, onClose }) {
  const [downloading, setDownloading] = useState(false)

  if (!invoice) return null

  const expiry = invoice.subscriptionPlan === 'Unlimited Plan'
    ? 'Never (Unlimited)'
    : invoice.expirationDate ? fmt(invoice.expirationDate) : '—'

  // Display total: use admin draft total if present, otherwise recompute
  const displayTotal = (() => {
    if (invoice.invoiceDraft?.lineItems?.length) {
      return invoice.invoiceDraft.lineItems.reduce(
        (sum, it) => sum + (Number(it.totalPrice) || 0), 0
      )
    }
    return invoice.isAirline
      ? resolveAirlineTotal(invoice)
      : Number(invoice.amount) || 0
  })()

  const handleDownload = async () => {
    setDownloading(true)
    try {
      await downloadInvoicePDF(invoice)
    } catch (err) {
      console.error('PDF generation failed:', err)
      alert('Could not generate PDF. Please try again.')
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="fixed inset-0 z-[60] bg-slate-900/70 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl border border-slate-200 overflow-hidden">

        {/* Header */}
        <div className="border-b border-slate-100 bg-slate-50 px-6 py-5 flex items-center justify-between">
          <div>
            <p className="text-[10px] font-black uppercase tracking-widest text-emerald-600 mb-1">Payment Successful</p>
            <h2 className="text-lg font-extrabold text-slate-900">Your Invoice</h2>
          </div>
          <button onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-lg border border-slate-200 text-slate-400 hover:bg-slate-100 transition">
            ✕
          </button>
        </div>

        {/* Invoice Preview */}
        <div className="px-6 py-5 space-y-4">

          {/* Paid badge + invoice number */}
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700 px-3 py-1 text-[10px] font-black uppercase tracking-widest">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
              Paid
            </span>
            <span className="text-xs text-slate-400">{invoice.invoiceNumber}</span>
          </div>

          {/* Summary card */}
          <div className="rounded-xl border border-slate-200 bg-slate-50 divide-y divide-slate-100 overflow-hidden">
            <div className="px-4 py-3 flex justify-between items-center">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Subscription Plan</span>
              <span className="text-sm font-bold text-slate-900">{invoice.subscriptionPlan}</span>
            </div>
            <div className="px-4 py-3 flex justify-between items-center">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Billed To</span>
              <span className="text-sm font-bold text-slate-900">{invoice.name}</span>
            </div>
            <div className="px-4 py-3 flex justify-between items-center">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Start Date</span>
              <span className="text-sm font-bold text-slate-900">{fmt(invoice.paidAt)}</span>
            </div>
            <div className="px-4 py-3 flex justify-between items-center">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Expiration</span>
              <span className={`text-sm font-bold ${expiry === 'Never (Unlimited)' ? 'text-emerald-600' : 'text-slate-900'}`}>{expiry}</span>
            </div>
            <div className="px-4 py-3 flex justify-between items-center bg-slate-900 rounded-b-xl">
              <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Total Paid</span>
              {/* Uses draft total when admin has edited, otherwise pricePerCert × holderCount */}
              <span className="text-xl font-black text-white">
                ${displayTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}
              </span>
            </div>
          </div>

          <p className="text-[11px] text-slate-400 text-center">
            Payment ID: <span className="font-mono">{invoice.paymentId}</span>
          </p>
        </div>

        {/* Actions */}
        <div className="px-6 pb-6 flex gap-3">
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="flex-1 inline-flex items-center justify-center gap-2 bg-red-600 hover:bg-red-700 text-white font-bold py-3 rounded-xl text-sm transition-all shadow-md shadow-red-200 disabled:opacity-60"
          >
            {downloading ? (
              <>
                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" className="opacity-20" />
                  <path fill="currentColor" d="M12 2a10 10 0 0 1 10 10h-4a6 6 0 0 0-6-6V2Z" />
                </svg>
                Generating PDF…
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0-3-3m3 3 3-3M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                </svg>
                Download PDF Invoice
              </>
            )}
          </button>
          <button onClick={onClose}
            className="flex-1 rounded-xl border border-slate-200 bg-white py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50 transition">
            Close
          </button>
        </div>
      </div>
    </div>
  )
}
